name: Deploy nuget
on:
  workflow_dispatch:
  workflow_call:
    secrets:
      NUGET_API_KEY:
        required: true

jobs:
  build:
    name: "🛠️ Build"
    uses: equinor/into-rdf/.github/workflows/build.yml@main

  upload-nuget:
    name: "📦 Upload nuget package"
    needs: [build]
    permissions:
      id-token: write
      contents: read
    uses: equinor/into-rdf/.github/workflows/publish.yml@main
    with:
      ARTIFACT: ${{ needs.build.outputs.artifact-name }}
    secrets:
      NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
