name: Publish
on:
  workflow_call:
    inputs:
      artifact:
        required: true
        type: string
    secrets:
      NUGET_API_KEY:
        required: true

jobs:
  publish:
    environment: ${{ inputs.env }}
    runs-on: ubuntu-latest

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: ${{ inputs.artifact }}
      - name: Setup .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 7.0.x
      - name: Debug 1
        shell: bash
        run: |
          find . -iname ${{ inputs.artifact }}
      - name: Debug 2
        shell: bash
        run: |
          pwd
      - name: Debug 3
        shell: bash
        run: |
          ls
      - name: Publish
        run: dotnet nuget push ${{ inputs.artifact }} --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json
