name: Synchronize csproj Version
on:
  workflow_dispatch:
  workflow_call:

env:
  PR_BRANCH: release-please--branches--main--components--intordf

jobs:
  sync-version:
    name: Synchronize CSPROJ version
    runs-on: ubuntu-latest
    steps:
      - name: Synchronize CSPROJ version
        uses: ./.github/actions/sync-dotnet-version
        with:
          branch: ${{ env.PR_BRANCH }}
          csproj-path: "IntoRdf/IntoRdf.csproj"
          version-file-path: "version.txt"
